# Generated by Django 5.1.15 on 2026-06-05 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='简介(Markdown)')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('rule_type', models.CharField(choices=[('acm', 'ACM/ICPC 模式'), ('oi', 'OI 模式')], default='acm', max_length=8)),
                ('visibility', models.CharField(choices=[('public', '公开'), ('private', '私有（指定用户）'), ('class', '指定班级'), ('password', '密码报名')], default='public', max_length=16)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('penalty_minutes', models.PositiveIntegerField(default=20, verbose_name='每次错误提交罚时(分钟)')),
                ('freeze_minutes', models.PositiveIntegerField(default=0, verbose_name='结束前封榜(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='classes.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contest', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=8, verbose_name='展示序号(A/B/C)')),
                ('score', models.PositiveIntegerField(default=100, verbose_name='分值')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
            ],
            options={
                'ordering': ['label'],
                'unique_together': {('contest', 'problem')},
            },
        ),
    ]
