# Generated by Django 5.1.15 on 2026-06-05 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=16)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('pending', '等待中'), ('judging', '判题中'), ('accepted', '通过'), ('wa', '答案错误'), ('tle', '超时'), ('mle', '内存超限'), ('re', '运行时错误'), ('ce', '编译错误'), ('pe', '格式错误'), ('ole', '输出超限'), ('se', '系统错误')], default='pending', max_length=8)),
                ('score', models.PositiveIntegerField(default=0)),
                ('time_used', models.PositiveIntegerField(default=0)),
                ('memory_used', models.PositiveIntegerField(default=0)),
                ('compile_error', models.TextField(blank=True, default='')),
                ('first_failed_index', models.IntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', '等待中'), ('judging', '判题中'), ('accepted', '通过'), ('wa', '答案错误'), ('tle', '超时'), ('mle', '内存超限'), ('re', '运行时错误'), ('ce', '编译错误'), ('pe', '格式错误'), ('ole', '输出超限'), ('se', '系统错误')], max_length=8)),
                ('time_used', models.PositiveIntegerField(default=0)),
                ('memory_used', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('input_preview', models.TextField(blank=True, default='')),
                ('expected_output', models.TextField(blank=True, default='')),
                ('actual_output', models.TextField(blank=True, default='')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='submissions.submission')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem'], name='submissions_user_id_1304bb_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submissions_status_c2b4f2_idx'),
        ),
    ]
