# Generated by Django 5.1.15 on 2026-06-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontestresult',
            name='group',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
