# Generated by Django 5.1.15 on 2026-06-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submissiontestresult_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='cloze_answers',
            field=models.JSONField(blank=True, default=dict, verbose_name='填空答案'),
        ),
    ]
