# Generated by Django 5.1.15 on 2026-06-05 02:01

import apps.problems.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(max_length=32, unique=True, verbose_name='题号')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='easy', max_length=16)),
                ('description', models.TextField(blank=True, default='', verbose_name='题目描述（Markdown）')),
                ('input_description', models.TextField(blank=True, default='', verbose_name='输入说明')),
                ('output_description', models.TextField(blank=True, default='', verbose_name='输出说明')),
                ('samples', models.JSONField(default=list, verbose_name='样例')),
                ('hint', models.TextField(blank=True, default='', verbose_name='提示')),
                ('source', models.CharField(blank=True, default='', max_length=255, verbose_name='来源')),
                ('time_limit', models.PositiveIntegerField(default=1000, verbose_name='时间限制(ms)')),
                ('memory_limit', models.PositiveIntegerField(default=256, verbose_name='内存限制(MB)')),
                ('compare_mode', models.CharField(choices=[('default', '默认（忽略行末空格）'), ('strict', '严格逐字节'), ('float', '浮点误差')], default='default', max_length=16)),
                ('float_precision', models.FloatField(default=1e-06, verbose_name='浮点精度')),
                ('spj_enabled', models.BooleanField(default=False, verbose_name='启用 SPJ')),
                ('spj_language', models.CharField(blank=True, default='cpp', max_length=16, verbose_name='SPJ 语言')),
                ('spj_code', models.TextField(blank=True, default='', verbose_name='SPJ 源代码')),
                ('allowed_languages', models.JSONField(default=apps.problems.models.default_languages, verbose_name='允许语言')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('hidden', '隐藏（草稿）'), ('contest', '仅竞赛可见'), ('class', '仅指定班级可见')], default='hidden', max_length=16)),
                ('total_submit', models.PositiveIntegerField(default=0)),
                ('accepted_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problems', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='problems', to='problems.tag')),
            ],
            options={
                'ordering': ['display_id'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(verbose_name='序号')),
                ('input_file', models.FileField(upload_to='testcases/', verbose_name='输入(.in)')),
                ('output_file', models.FileField(upload_to='testcases/', verbose_name='输出(.out)')),
                ('score', models.PositiveIntegerField(default=10, verbose_name='分值(OI模式)')),
                ('is_sample', models.BooleanField(default=False, verbose_name='是否样例/可见')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('problem', 'index')},
            },
        ),
    ]
