# Generated by Django 5.1.15 on 2026-06-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('unrated', '暂无评定'), ('entry', '入门'), ('pop_minus', '普及−'), ('pop', '普及/提高−'), ('pop_plus', '普及+/提高'), ('imp_plus', '提高+/省选−'), ('provincial', '省选/NOI−'), ('noi', 'NOI/NOI+/CTSC')], default='entry', max_length=16),
        ),
    ]
