# Generated by Django 5.1.15 on 2026-06-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_remap_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='group',
            field=models.PositiveIntegerField(default=0, verbose_name='子任务组(0=独立计分；同组捆绑：全过才得分)'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='score',
            field=models.PositiveIntegerField(default=10, verbose_name='分值'),
        ),
    ]
