# Generated by Django 5.1.15 on 2026-06-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_testcase_group_alter_testcase_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='cloze_answers',
            field=models.JSONField(blank=True, default=dict, verbose_name='填空参考答案'),
        ),
        migrations.AddField(
            model_name='problem',
            name='cloze_language',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='填空语言'),
        ),
        migrations.AddField(
            model_name='problem',
            name='cloze_template',
            field=models.TextField(blank=True, default='', verbose_name='填空模板'),
        ),
        migrations.AddField(
            model_name='problem',
            name='cloze_use_judge',
            field=models.BooleanField(default=False, verbose_name='填空-是否评测机判定'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(choices=[('standard', '标准题'), ('cloze', '程序填空题')], default='standard', max_length=16, verbose_name='题型'),
        ),
    ]
