# Generated by Django 5.1.15 on 2026-06-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='granted_permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='额外权限'),
        ),
    ]
